version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - '7000:7000'
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}

    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    restart: always
